#!/usr/bin/env sh
set -eu

# One-command bootstrap for a fresh Ubuntu/Debian server.
# - installs docker (if missing)
# - clones/updates repo
# - generates .env.server with strong secrets (no secrets in git)
# - starts services with docker compose
#
# Usage (run on server):
#   curl -fsSL https://raw.githubusercontent.com/Uz11ps/klanymobail/main/infra/deploy/bootstrap.sh | sh

REPO_URL="https://github.com/Uz11ps/klanymobail.git"
APP_DIR="/opt/klanymobail"

need_cmd() {
  command -v "$1" >/dev/null 2>&1
}

rand() {
  # URL-safe random string (48 bytes -> ~64 chars)
  dd if=/dev/urandom bs=48 count=1 2>/dev/null | base64 | tr -d '\n' | tr '+/' '-_'
}

echo "[bootstrap] ensure system deps"
if ! need_cmd git; then
  apt-get update -y
  apt-get install -y git ca-certificates curl
fi

if ! need_cmd docker; then
  echo "[bootstrap] installing docker"
  apt-get update -y
  apt-get install -y ca-certificates curl gnupg
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg

  . /etc/os-release
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    ${VERSION_CODENAME} stable" > /etc/apt/sources.list.d/docker.list

  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
fi

mkdir -p "$APP_DIR"
if [ -d "$APP_DIR/.git" ]; then
  echo "[bootstrap] updating repo"
  git -C "$APP_DIR" fetch --all --prune
  git -C "$APP_DIR" reset --hard origin/main
else
  echo "[bootstrap] cloning repo"
  rm -rf "$APP_DIR"
  git clone "$REPO_URL" "$APP_DIR"
fi

SERVER_IP="$(curl -fsSL https://api.ipify.org || echo "")"
if [ -z "$SERVER_IP" ]; then SERVER_IP="91.197.99.149"; fi

echo "[bootstrap] writing .env.server"
cat > "$APP_DIR/.env.server" <<EOF
# Auto-generated by infra/deploy/bootstrap.sh
HTTP_PORT=8782
API_PORT=3000

JWT_SECRET=$(rand)
CRON_SECRET=$(rand)

ADMIN_SEED_EMAIL=123@mail.ru
ADMIN_SEED_PASSWORD=123

POSTGRES_DB=klany
POSTGRES_USER=klany
POSTGRES_PASSWORD=$(rand)
POSTGRES_PORT=5434

MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=$(rand)
MINIO_PORT=9000
MINIO_CONSOLE_PORT=9001
MINIO_ENDPOINT=minio
MINIO_USE_SSL=false
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=$(rand)
MINIO_BUCKET_QUEST_EVIDENCE=quest-evidence
MINIO_BUCKET_SHOP_PRODUCTS=shop-products
MINIO_PUBLIC_BASE_URL=http://$SERVER_IP:9000

YOOKASSA_SHOP_ID=
YOOKASSA_SECRET_KEY=
YOOKASSA_RETURN_URL=http://$SERVER_IP:8782
TELEGRAM_BOT_TOKEN=
EOF

echo "[bootstrap] starting services"
cd "$APP_DIR"
docker compose --env-file .env.server up -d --build

echo "[bootstrap] done"
echo "[bootstrap] admin: http://$SERVER_IP:8782  (login 123@mail.ru / 123)"

